dateModified: 1606787321
email:
  fromEmail: $MAILER_FROM_ADDRESS
  fromName: 'Craft CMS'
  replyToEmail: null
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
system:
  edition: solo
  live: true
  name: 'Heroku Test'
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
