dateModified: 1651781655
email:
  fromEmail: $MAILER_FROM_ADDRESS
  fromName: 'Heroku Test'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5881a7a7-7f97-4a4e-a665-b0a6871fff48: 'Heroku Test' # Heroku Test
    3542129a-7eb9-4b3e-9022-e532a6b99446: Common # Common
    eb5db02d-52e0-4807-9105-7a6c5ec66ccd: 'Heroku Test' # Heroku Test
system:
  edition: solo
  live: true
  name: 'Heroku Test'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
